### ISSUE TITLE
How to restore tmux status line while quit vim?

### ISSUE THREAD

**Issue by fgheng** [narajaon/onestatus#15]
Hello, this plugin is great, thanks for your work, But how to restore tmux status line while I quit vim, thank you very much.

**Comment by tusqasi** [comment]
Put this in your `$MYVIMRC`  

`au ExitPre * :!tmux source ~/your_default_tumx.conf`

this will source the tmux file you had before entering vim, when you exit vim.

**Comment by fgheng** [comment]
woks, thank you very much
