### ISSUE TITLE
Does it support show line number in tmux status line?

### ISSUE THREAD

**Issue by fgheng** [narajaon/onestatus#16]
Hello, does it support show line number in tmux status line?

**Comment by tusqasi** [comment]
That will be no, for now at least, because how the plugin is implemented.
Onestatus is refreshed each time you enter a buffer.
for the line numbers to work, the status line must be updated each time you move your cursor.

**Comment by tusqasi** [comment]
a rudimentary implementation though
put this in `$MYVIMRC`
```
fun g:LineNow()
  let lineCur = line('.')
  return lineCur
endfunc

au CursorMoved * :OneStatus
```
and this your onestatus.json
```  
"status-left": [
    { "fg": "default", "bg": "default", "labelFunc": "s:getFileName" },
    { "fg": "default", "bg": "default", "labelFunc": "LineNow" }    
  ],

```

**Comment by fgheng** [comment]
I see, thank you very much
