### ISSUE TITLE
tmux configs not working as expected

### ISSUE THREAD

**Issue by zeitchef** [narajaon/onestatus#17]
Hi there, very cool plugin and just what I've been looking for. I'm running into the issue where changes I make to the `onestatus.json` file aren't being recognized. I assume the keys in this json file are just mapped to tmux configurations?

For example, I assume setting `"status-justify": "center"` maps directly to `set-option -g status-justify center` that I have in my `.tmux.conf`... is this a correct assumption? It's not super clear in the README.

Also, I don't seem to be able to access tmux "variables". For example, how would I implement the following, accessing the current tmux session name:

`set-option -g status-left "#[fg=#e2e4e5,bg=#43454f] #S "`

Many thanks, and keep up the great work!

**Comment by tusqasi** [comment]
Hey @zeitchef, check out the readme and while you do that, let me take a look at your `onestatus.json` and `$MYVIMRC`.

**Comment by zeitchef** [comment]
```
// onestatus.json
{
  "status-right": [
    { "fg": "#34353e", "bg": "default", "labelFunc": "s:getCWD" }
  ],
  "status-left": [
    { "fg": "#34353e", "bg": "#5af78e", "labelFunc": "s:getHead" },
    { "fg": "default", "bg": "default", "labelFunc": "s:getFileName" }
  ],
  "status-style": "s:getDefaultColor",
  "status-justify": "center", <-- this seems to be a problem
  "window-status-style": [
    { "fg": "#6c757d", "bg": "default", "isStyleOnly": true }
  ],
  "window-status-current-style": [
    { "fg": "#34353e", "bg": "#57c7ff", "isStyleOnly": true }
  ]
}
```
And the relevant vim configs:
```
au BufEnter * :OneStatus
au ExitPre * :!tmux source ~/.tmux.conf
set noshowmode noruler
set laststatus=0
```

**Comment by tusqasi** [comment]
It's still WIP. To get desired changes you can change the line in `plugin/onestatus.vim` like this
```vim
if g:onestatus_default_layout == 1
  call onestatus#build([
        \{'command' : 'set-option status-justify centre'},
        \{'command': 'set-option status-right-length ' . g:onestatus_right_length},
        \{'command': 'set-option status-left-length ' . g:onestatus_left_length},
        \])
endif
```
And as for your question
> For example, I assume setting "status-justify": "center" maps directly to set-option -g status-justify center that I have in my .tmux.conf... is this a correct assumption? It's not super clear in the README.
No, it doesn't. Internally, that json object is taken and `fg`, `bg`, `lableFunc` are looked for and then the values are mapped in a structured way, which makes configuration like `status-justify : 'center'` not work as expected.

Changes will come. Stay tuned.

**Comment by tusqasi** [comment]
And for

>Also, I don't seem to be able to access tmux "variables". For example, how would I implement the following, accessing the current tmux session name:  
>`set-option -g status-left "#[fg=#e2e4e5,bg=#43454f] #S "`

This should work like
```
  "status-left": [
    { "fg": "#34353e", "bg": "#5af78e", "label": "#S" },
  ],
```
For setting a textual 'thing' you can use label.
It will work same as you expected.

**Comment by zeitchef** [comment]
Thanks. I overlooked the differences between `label` and `labelFunc`. This definitely pushed me further. Looking forward to future iterations!

**Comment by narajaon** [comment]
Hello, thanks for the feedbacks. 
You indeed have to use the label attribute for plain strings or tmux variables like `#S`.
As for for `"status-justify": "center"`, I suggest putting everything that won't change in your tmux.conf file.
Let onestatus handle the dynamic updates.

That being said, since `status-justify` is directly linked to your status even though it should not change, I might add it in the future.
