### ISSUE TITLE
Error when calling OneStatus

### ISSUE THREAD

**Issue by jamespeapen** [narajaon/onestatus#21]
Hi, I just downloaded the plugin, but when I call it, I get this error:

```Error detected while processing function <SNR>84_onestatusDefault[6]..<SNR>84_getConfig:
line    1:
E730: using List as a String
Error detected while processing function onestatus#build:
line    3:
E715: Dictionary required
```
I have the default `onestatus.json`.
Thanks

**Comment by tusqasi** [comment]
make sure you copied the onestatus.json properly.

**Comment by jamespeapen** [comment]
I checked and re-pasted the json again, but the error persists.
Here's the output of `cat onestatus.json`:

```json
{
  "status-right": [
    { "fg": "#ffd167", "bg": "default", "label": "" },
    { "fg": "#218380", "bg": "#ffd167", "labelFunc": "s:getCWD" },
    { "fg": "#218380", "bg": "#ffd167", "label": "" },
    { "fg": "#fcfcfc", "bg": "#218380", "labelFunc": "s:getHead" }
  ],
  "status-left": [
    { "fg": "default", "bg": "default", "labelFunc": "s:getFileName" }
  ],
  "status-style": "s:getDefaultColor",
  "window-status-style": [
    { "fg": "#6c757d", "bg": "default", "isStyleOnly": true }
  ],
  "window-status-current-style": [
    { "fg": "#ffd167", "bg": "default", "isStyleOnly": true }
  ]
}
```

**Comment by tusqasi** [comment]
What did you use to download the plugin?

**Comment by jamespeapen** [comment]
vim-plug

**Comment by narajaon** [comment]
Hello, thanks for using my plugin !

- Can you detail the steps you took to install the plugin
- Are you using vim or neovim ? What version ?
- Did you put the `onestatus.json` in the correct directory as suggested by the readme ?
- Do you have the right permissions on the file ?

**Comment by jamespeapen** [comment]
- I added 'narajaon/onestatus' to my vimrc and ran `PlugInstall`.
- Vim 8.2
- I put it in $HOME.
- The file has read and write permissions

**Comment by tusqasi** [comment]
Hey, @jamespeapen any updates.

**Comment by jamespeapen** [comment]
I hadn't used it in a while, but I just tried it with neovim and it works. However, it doesn't update when I open a new tmux window. The new window retains the statusline of the window with vim. It's loaded with 

```vim
Plug 'narajaon/onestatus`
```

and I use this at the end of my init.vim

```vim
if !empty($TMUX)
    au BufEnter,BufLeave,FocusGained * :OneStatus
    au VimLeave * :OneStatusClean
    set noshowmode noruler
    set laststatus=0
endif
```

I have the example config file in the nvim config folder. Is there a setting needed in my 
[tmux.conf](https://github.com/jamespeapen/dotfiles/blob/master/tmux.conf) to update the statusline when making a new window?

**Comment by tusqasi** [comment]
I think this fixed with the latest release.

Try using it, if you still need it.

**Comment by jamespeapen** [comment]
It's updated but that behavior persists.
